service: chop-example

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-west-1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  api:
    handler: bin/handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY